name: Setup kind
description: Deploy kind cluster

runs:
  using: composite
  steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1
      with:
        # https://github.com/helm/kind-action?tab=readme-ov-file#inputs
        verbosity: 10
        cluster_name: "kind-ci-${{ github.job }}"
        ignore_failed_clean: true # Ignore the post delete cluster action failing
        wait: "180s" # Max timeout to wait Kind becomes ready

    - name: Print Kind cluster state
      run: |
        kubectl cluster-info
        kubectl get pods -A
        kubectl describe node
      shell: bash