name: Prepare integration tests
description: Prepare integration tests

inputs:
  spark_version:
    description: Spark version
    required: true
  scala_version:
    description: Scala version
    required: true
  java_version:
    description: Java version
    required: true

outputs:
  git_tag_checkout_dir:
    description: "Git checkout tag local source directory"
    value: ${{ steps.git-checkout-tag.outputs.git_tag_checkout_dir }}

runs:
  using: composite
  steps:
    - name: Set up Java ${{ inputs.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java_version }}

    - name: Cache Scala, SBT and Maven
      uses: actions/cache@v4
      with:
        path: |
          build/apache-maven-*
          build/scala-*
          build/*.jar
          ~/.sbt
        key: build-${{ inputs.spark_version }}-scala${{ inputs.scala_version }}-java${{ inputs.java_version }}

    - name: Cache Coursier local repository
      uses: actions/cache@v4
      with:
        path: ~/.cache/coursier
        key: build-${{ inputs.spark_version }}-scala${{ inputs.scala_version }}-java${{ inputs.java_version }}-coursier



