#
# Copyright 2024 tosit.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: ci 

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".build/**"

      - "spark/**"
      - "spark-*/**"
  
      - "!README.md"

  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".build/**"
  
      - "spark/**"
      - "spark-*/**"
  
      - "!README.md"

  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # Only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  
jobs:

  get-ci-versions:
    runs-on: "ubuntu-latest"
    outputs:
      matrix: ${{ steps.ci-versions.outputs.matrix }}
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v4

      - name: Get CI versions matrix 📥
        id: ci-versions
        uses: ./.github/actions/spark-version-matrix
        with:
          ci_only: "true"

  spark-ci:
    name: spark-ci (spark-${{ matrix.version.spark_version }})
    needs: [get-ci-versions]
    strategy:
      matrix: 
        version: ${{ fromJson(needs.get-ci-versions.outputs.matrix) }}
    uses: ./.github/workflows/build-images-template.yml
    with:
      python_version: ${{ matrix.version.python_version }}
      spark_version: ${{ matrix.version.spark_version }}
      java_version: ${{ matrix.version.java_version }}
      scala_version: ${{ matrix.version.scala_version }}
      hadoop_version: ${{ matrix.version.hadoop_version }}
      publish_to_registry: "false"
