name: release-please

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # Only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'idirze' && github.event.pull_request.merged == true
    steps:
      - uses: google-github-actions/release-please-action@v4

